server:
  port: 88

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.250:8848
    gateway:
      routes:
        - id: rout1
          uri: http://www.baidu.com
          predicates:
            - Query=url, baidu
        - id: rout2
          uri: http://www.qq.com
          predicates:
            - Query=url, qq